version: "3"
services:
  # NODE 1
  redis1:
    image: redis:4.0.11
    ports: ['6379:6379']
  node1:
    build: ./app
    entrypoint:
      - gunicorn
      - -b :5000
      - -t 1000
      - -k gevent
      - --reload
      - application
    environment:
      REDIS_URL: 'redis1'
      ETH_RPC_PROVIDER: ${ETH_RPC_PROVIDER}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ./application.py
      NODE_ADDRESS: '***REMOVED***'
      NODE_PRIVATE_KEY: '***REMOVED***'
      EVENT_REGISTRY_ADDRESS: ${EVENT_REGISTRY_ADDRESS}
      NODE_REGISTRY_ADDRESS: ${NODE_REGISTRY_ADDRESS}
      NODE_IP: 'host.docker.internal'
      NODE_PORT: 81
      WERKZEUG_RUN_MAIN: 'true'
    ports: 
        - '81:5000'
        - '8186:8765'
    volumes: ['./app:/app']
    depends_on:
      - redis1
    links:
      - redis1
  # NODE 2
  redis2:
    image: redis:4.0.11
  node2:
    build: ./app
    entrypoint:
      - gunicorn
      - -b :5000
      - -t 1000
      - -k gevent
      - --reload
      - application
    environment:
      REDIS_URL: 'redis2'
      ETH_RPC_PROVIDER: ${ETH_RPC_PROVIDER}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ./application.py
      NODE_ADDRESS: '***REMOVED***'
      NODE_PRIVATE_KEY: '***REMOVED***'
      EVENT_REGISTRY_ADDRESS: ${EVENT_REGISTRY_ADDRESS}
      NODE_REGISTRY_ADDRESS: ${NODE_REGISTRY_ADDRESS}
      NODE_IP: 'host.docker.internal'
      NODE_PORT: 82
      WERKZEUG_RUN_MAIN: 'true'
    ports: 
        - '82:5000'
        - '8286:8765'
    volumes: ['./app:/app']
    depends_on:
      - redis2
    links:
      - redis2
  # NODE 3
  redis3:
    image: redis:4.0.11
  node3:
    build: ./app
    entrypoint:
      - gunicorn
      - -b :5000
      - -t 1000
      - -k gevent
      - --reload
      - application
    environment:
      REDIS_URL: 'redis3'
      ETH_RPC_PROVIDER: ${ETH_RPC_PROVIDER}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ./application.py
      NODE_ADDRESS: '***REMOVED***'
      NODE_PRIVATE_KEY: '***REMOVED***'
      EVENT_REGISTRY_ADDRESS: ${EVENT_REGISTRY_ADDRESS}
      NODE_REGISTRY_ADDRESS: ${NODE_REGISTRY_ADDRESS}
      NODE_IP: 'host.docker.internal'
      NODE_PORT: 83
      WERKZEUG_RUN_MAIN: 'true'
    ports:
        - '83:5000'
        - '8386:8765'
    volumes: ['./app:/app']
    depends_on:
      - redis3
    links:
      - redis3
