version: "3"
services:
  # NODE 1
  redis1:
    image: redis:4.0.11
    ports: ['6379:6379']
  node1:
    build: ./app
    entrypoint: "gunicorn -b :5000 -t 1000 -k gevent --access-logfile '-' --reload application"
    environment:
      DB_REDIS_IP: 'redis1'
      ETH_RPC_PROVIDER: ${ETH_RPC_PROVIDER}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ./application.py
      SENTRY_DSN: ${SENTRY_DSN}
      NODE_ADDRESS: '***REMOVED***'
      NODE_PRIVATE_KEY: '***REMOVED***'
      EVENT_REGISTRY_ADDRESS: ${EVENT_REGISTRY_ADDRESS}
      NODE_REGISTRY_ADDRESS: ${NODE_REGISTRY_ADDRESS}
      NODE_IP: 'host.docker.internal'
      HTTP_PORT: 81
      WEBSOCKET_PORT: 8781
      USE_HTTPS: 'false'
    ports: 
        - '81:5000'
        - '8781:8781'
    volumes: ['./app:/app']
    depends_on:
      - redis1
    links:
      - redis1
  # NODE 2
  redis2:
    image: redis:4.0.11
  node2:
    build: ./app
    entrypoint: "gunicorn -b :5000 -t 1000 -k gevent --access-logfile '-' --reload application"
    environment:
      DB_REDIS_IP: 'redis2'
      ETH_RPC_PROVIDER: ${ETH_RPC_PROVIDER}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ./application.py
      SENTRY_DSN: ${SENTRY_DSN}
      NODE_ADDRESS: '***REMOVED***'
      NODE_PRIVATE_KEY: '***REMOVED***'
      EVENT_REGISTRY_ADDRESS: ${EVENT_REGISTRY_ADDRESS}
      NODE_REGISTRY_ADDRESS: ${NODE_REGISTRY_ADDRESS}
      NODE_IP: 'host.docker.internal'
      HTTP_PORT: 82
      WEBSOCKET_PORT: 8782
      USE_HTTPS: 'false'
    ports: 
        - '82:5000'
        - '8782:8782'
    volumes: ['./app:/app']
    depends_on:
      - redis2
    links:
      - redis2
  # NODE 3
  redis3:
    image: redis:4.0.11
  node3:
    build: ./app
    entrypoint: "gunicorn -b :5000 -t 1000 -k gevent --access-logfile '-' --reload application"
    environment:
      DB_REDIS_IP: 'redis3'
      ETH_RPC_PROVIDER: ${ETH_RPC_PROVIDER}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ./application.py
      NODE_ADDRESS: '***REMOVED***'
      NODE_PRIVATE_KEY: '***REMOVED***'
      EVENT_REGISTRY_ADDRESS: ${EVENT_REGISTRY_ADDRESS}
      NODE_REGISTRY_ADDRESS: ${NODE_REGISTRY_ADDRESS}
      NODE_IP: 'host.docker.internal'
      HTTP_PORT: 83
      WEBSOCKET_PORT: 8783
      USE_HTTPS: 'false'
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
        - '83:5000'
        - '8783:8783'
    volumes: ['./app:/app']
    depends_on:
      - redis3
    links:
      - redis3
